services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
        - ./backend:/app
    env_file:
        - ./backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:5173
    volumes:
        - ./frontend:/app
        - /app/node_modules
    command: npm run dev

  redis:
    image: redis:7
    ports:
      - 6379:6379

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
        - ./backend:/app
    env_file:
      - ./backend/.env
    command: celery -A celery_stuff.celery_app worker --loglevel=info --pool=threads
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: celery -A celery_stuff.celery_app beat --loglevel=info
    depends_on:
      - redis

  backend_tests:
    build:
      context: ./backend
      dockerfile: Dockerfile.tests
    volumes:
        - .:/app
    entrypoint: []
    container_name: backend_test



